### PR TITLE
Update monitors.tf to monitor grafana from uptimerobot

### PR DESCRIPTION
**Pull request by jacopen**
# Description

Modify tf file to monitor grafana from uptimerobot.

Fixes # (issue)

## Type of change

- [ ] Document update or simple typo fix
- [ ] Maintenance/update components
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] I have checked backward/forward compatibility that may cause regarding this change.

### CODE REVIEW

**Comment by jacopen** [comment]
plan結果

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # uptimerobot_monitor.dreamkast-by-terraform will be updated in-place
  ~ resource "uptimerobot_monitor" "dreamkast-by-terraform" {
      ~ friendly_name       = "Dreamkast by Terraform" -> "Dreamkast"
        id                  = "789889763"
        # (6 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # uptimerobot_monitor.grafana will be created
  + resource "uptimerobot_monitor" "grafana" {
      + friendly_name = "Grafana"
      + id            = (known after apply)
      + interval      = 60
      + status        = (known after apply)
      + type          = "http"
      + url           = "https://grafana.cloudnativedays.jp"

      + alert_contact {
          + id = "3411849"
        }
      + alert_contact {
          + id = "01534246"
        }
    }

  # uptimerobot_monitor.website-by-terraform will be updated in-place
  ~ resource "uptimerobot_monitor" "website-by-terraform" {
      ~ friendly_name       = "Website by Terraform" -> "Website"
        id                  = "789889883"
        # (6 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 1 to add, 2 to change, 0 to destroy.
```

**Review by mhoshi-vm — CHANGES_REQUESTED** [review]
LGTM

**Comment by jacopen** [comment]
LGTMなのにRequested changes😱

**Comment by mhoshi-vm** [comment]
失礼w！

**Pull request merged**
